server.port=8081
spring.datasource.url=jdbc:h2:file:./importador-arquivos-h2-db
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-bean-definition-overriding=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
springdoc.swagger-ui.path:/swagger-ui.html

#importador-arquivos.cron: '0 0/5 * * * ?'
importador-arquivos.cron: '0/5 * * * * ?'
importador-arquivos.data.in: /home/castgroup/data/in
importador-arquivos.data.out: /home/castgroup/data/out